
let BOOK=null;
const state={chapter:0,tab:'contents',font:19,dark:false,bookmarks:[],scroll:{}};
const $=id=>document.getElementById(id);
const esc=s=>(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadState(){try{Object.assign(state,JSON.parse(localStorage.getItem('readerState')||'{}'));}catch(e){};document.documentElement.style.setProperty('--reader-size',`${state.font||19}px`);document.body.classList.toggle('dark',!!state.dark)}
function saveState(){localStorage.setItem('readerState',JSON.stringify(state))}
function tgInit(){const tg=window.Telegram?.WebApp;if(!tg)return;tg.ready();tg.expand();try{tg.setHeaderColor(state.dark?'#151515':'#f4efe7');tg.setBackgroundColor(state.dark?'#151515':'#f4efe7')}catch(e){}}
function partFor(ch){return BOOK.parts.find(p=>p.number===ch.part)}
function setHome(){ $('homeView').classList.remove('hidden');$('readerView').classList.add('hidden');$('backBtn').classList.add('hidden');$('brand').textContent=BOOK.title;window.scrollTo(0,0);renderTab();}
function openChapter(index, restore=true){index=Math.max(0,Math.min(BOOK.chapters.length-1,index));state.chapter=index;saveState();const ch=BOOK.chapters[index];const part=partFor(ch);$('homeView').classList.add('hidden');$('readerView').classList.remove('hidden');$('backBtn').classList.remove('hidden');$('brand').textContent=`Chapter ${String(ch.number).padStart(2,'0')}`;$('chapterPart').textContent=`PART ${part.number} · ${part.title}`;$('chapterTitle').textContent=`${String(ch.number).padStart(2,'0')}  ${ch.title}`;$('chapterSubtitle').textContent=ch.subtitle||'';$('chapterSubtitle').classList.toggle('hidden',!ch.subtitle);$('chapterBody').innerHTML=ch.paragraphs.map(p=>p==='***'?'<div class="ornament">* * *</div>':`<p>${esc(p)}</p>`).join('');$('prevChapter').disabled=index===0;$('nextChapter').disabled=index===BOOK.chapters.length-1;updateBookmark();requestAnimationFrame(()=>{const y=restore?(state.scroll?.[index]||0):0;window.scrollTo(0,y);updateProgress();});}
function renderContents(){let h='';for(const p of BOOK.parts){h+=`<section class="part"><div class="eyebrow">PART ${p.number}</div><h3>${esc(p.title)}</h3>`;for(const ch of BOOK.chapters.filter(c=>c.part===p.number)){h+=`<button class="chapter-row" data-ch="${ch.number-1}"><span class="chapter-num">${String(ch.number).padStart(2,'0')}</span><span>${esc(ch.title)}${ch.subtitle?`<small>${esc(ch.subtitle)}</small>`:''}</span><span>›</span></button>`}h+='</section>'}$('tabPanel').innerHTML=h;document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>openChapter(+b.dataset.ch,false));}
function snippet(text,q){const lo=text.toLowerCase(),i=lo.indexOf(q.toLowerCase());const start=Math.max(0,i-80),end=Math.min(text.length,i+q.length+110);return (start?'…':'')+text.slice(start,end)+(end<text.length?'…':'')}
function renderSearch(){ $('tabPanel').innerHTML='<input id="searchInput" class="searchbox" placeholder="Search names, places, phrases…" autocomplete="off"><div id="searchResults" class="empty">Type at least 2 characters.</div>';const input=$('searchInput');input.oninput=()=>{const q=input.value.trim();const box=$('searchResults');if(q.length<2){box.className='empty';box.textContent='Type at least 2 characters.';return}const res=[];for(const ch of BOOK.chapters){const full=ch.paragraphs.join(' ');if((ch.title+' '+full).toLowerCase().includes(q.toLowerCase()))res.push({ch,s:snippet(ch.title+' — '+full,q)})}box.className='';box.innerHTML=res.length?res.map(r=>`<button class="result" data-result="${r.ch.number-1}"><b>Chapter ${String(r.ch.number).padStart(2,'0')} · ${esc(r.ch.title)}</b><p>${esc(r.s)}</p></button>`).join(''):'<div class="empty">No matches found.</div>';document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openChapter(+b.dataset.result,false));};setTimeout(()=>input.focus(),50)}
function renderBookmarks(){const nums=[...(state.bookmarks||[])].sort((a,b)=>a-b);if(!nums.length){$('tabPanel').innerHTML='<div class="empty">No bookmarks yet. Open a chapter and tap ☆ Bookmark.</div>';return}$('tabPanel').innerHTML=nums.map(i=>{const ch=BOOK.chapters[i];return `<button class="chapter-row" data-book="${i}"><span class="chapter-num">★</span><span>Chapter ${String(ch.number).padStart(2,'0')} · ${esc(ch.title)}</span><span>›</span></button>`}).join('');document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>openChapter(+b.dataset.book,true));}
function renderTab(){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===state.tab));if(state.tab==='search')renderSearch();else if(state.tab==='bookmarks')renderBookmarks();else renderContents();}
function updateBookmark(){const on=(state.bookmarks||[]).includes(state.chapter);$('bookmarkBtn').textContent=on?'★ Bookmarked':'☆ Bookmark'}
function toggleBookmark(){state.bookmarks=state.bookmarks||[];const i=state.bookmarks.indexOf(state.chapter);if(i>=0)state.bookmarks.splice(i,1);else state.bookmarks.push(state.chapter);saveState();updateBookmark()}
function updateProgress(){if($('readerView').classList.contains('hidden'))return;const max=document.documentElement.scrollHeight-innerHeight;const pct=max>0?Math.max(0,Math.min(1,scrollY/max)):0;$('progressBar').firstElementChild.style.width=(pct*100)+'%';state.scroll=state.scroll||{};state.scroll[state.chapter]=scrollY;saveState()}
function setTheme(){document.body.classList.toggle('dark',state.dark);document.querySelector('meta[name="theme-color"]').setAttribute('content',state.dark?'#151515':'#f4efe7');tgInit();saveState()}
async function boot(){loadState();tgInit();BOOK=await fetch('book.json').then(r=>r.json());$('continueBtn').textContent=(state.scroll&&Object.keys(state.scroll).length)?'Continue Reading':'Start Reading';$('continueBtn').onclick=()=>openChapter(state.chapter||0,true);$('backBtn').onclick=setHome;$('prevChapter').onclick=()=>openChapter(state.chapter-1,false);$('nextChapter').onclick=()=>openChapter(state.chapter+1,false);$('bookmarkBtn').onclick=toggleBookmark;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{state.tab=t.dataset.tab;saveState();renderTab()});$('settingsBtn').onclick=()=>$('settingsSheet').classList.remove('hidden');$('closeSettings').onclick=()=>$('settingsSheet').classList.add('hidden');$('settingsSheet').onclick=e=>{if(e.target===$('settingsSheet'))$('settingsSheet').classList.add('hidden')};$('fontDown').onclick=()=>{state.font=Math.max(15,(state.font||19)-1);document.documentElement.style.setProperty('--reader-size',state.font+'px');saveState()};$('fontUp').onclick=()=>{state.font=Math.min(28,(state.font||19)+1);document.documentElement.style.setProperty('--reader-size',state.font+'px');saveState()};$('themeToggle').onclick=()=>{state.dark=!state.dark;setTheme()};let ticking=false;addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(()=>{updateProgress();ticking=false});ticking=true}},{passive:true});setHome()}
boot().catch(err=>{document.body.innerHTML='<main style="padding:24px;font-family:sans-serif"><h2>Reader could not load</h2><p>'+esc(String(err))+'</p><p>This app must be opened from an HTTPS website (for example GitHub Pages), not directly as a local file.</p></main>'});
